version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.12.0
    - 0.12.2
    - 1.0.0
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: react-toastify
    versions:
    - 7.0.1
