name: Deploy project to a server

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.TOKEN_GITHUB }} -t "resume:latest" .
      - name: Save Docker image as tarball
        run: |
          docker save resume:latest -o resume.tar
      # - name: Upload tarball as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: gatsby-image-tarball
      #     path: my-gatsby-project.tar