name: Resume
on: [push]

jobs:
  Build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to dockerhub docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HOSTNAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ vars.HOSTNAME }}/sylflo/resume-frontend:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.TOKEN_GITHUB }}
          registry: ${{ vars.HOSTNAME }}
  Build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to dockerhub docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HOSTNAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ vars.HOSTNAME }}/sylflo/resume-backend:latest
          registry: ${{ vars.HOSTNAME }}
  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: [Build-frontend, Build-backend]
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #    - name: Install Ansible
  #      run: |
  #        sudo apt update
  #        sudo apt install -y ansible
  #    - name: Add SSH key
  #      uses: webfactory/ssh-agent@v0.9.0
  #      with:
  #        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #    - name: Create inventory file
  #      run: |
  #        cd deploy
  #        echo "[bastion]" > inventory
  #        echo "server-bastion ansible_host=${{ secrets.PUBLIC_IP_ADDRESS }} ansible_user=outscale" >> inventory
  #        echo "[seedbox]" >> inventory
  #        echo "server-seedbox ansible_host=10.1.6.10 ansible_user=outscale" >> inventory
  #        echo "[seedbox:vars]" >> inventory
  #        echo "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand=\"ssh -p 22 -W %h:%p -q outscale@${{ secrets.PUBLIC_IP_ADDRESS }}\"'" >> inventory
  #        cat inventory
  #    - name: Little check
  #      run: |
  #        ssh -o StrictHostKeyChecking=no outscale@${{ secrets.PUBLIC_IP_ADDRESS }} 'pwd'
  #    - name: Run Ansible Playbook
  #      run: |
  #        cd deploy
  #        echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_password.txt
  #        ansible-playbook --vault-password-file vault_password.txt -i inventory main.yml
